package com.cn.model.domain;

public class AddressLibrary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_library.id
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_library.country
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_library.province
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_library.city
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_library.county
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_library.specific_address
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    private String specificAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_library.consignee
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    private String consignee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_library.contact_information
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    private String contactInformation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_library.user_id
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_library.id
     *
     * @return the value of address_library.id
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_library.id
     *
     * @param id the value for address_library.id
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_library.country
     *
     * @return the value of address_library.country
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_library.country
     *
     * @param country the value for address_library.country
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_library.province
     *
     * @return the value of address_library.province
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_library.province
     *
     * @param province the value for address_library.province
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_library.city
     *
     * @return the value of address_library.city
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_library.city
     *
     * @param city the value for address_library.city
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_library.county
     *
     * @return the value of address_library.county
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_library.county
     *
     * @param county the value for address_library.county
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_library.specific_address
     *
     * @return the value of address_library.specific_address
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    public String getSpecificAddress() {
        return specificAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_library.specific_address
     *
     * @param specificAddress the value for address_library.specific_address
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    public void setSpecificAddress(String specificAddress) {
        this.specificAddress = specificAddress == null ? null : specificAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_library.consignee
     *
     * @return the value of address_library.consignee
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_library.consignee
     *
     * @param consignee the value for address_library.consignee
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_library.contact_information
     *
     * @return the value of address_library.contact_information
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    public String getContactInformation() {
        return contactInformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_library.contact_information
     *
     * @param contactInformation the value for address_library.contact_information
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    public void setContactInformation(String contactInformation) {
        this.contactInformation = contactInformation == null ? null : contactInformation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_library.user_id
     *
     * @return the value of address_library.user_id
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_library.user_id
     *
     * @param userId the value for address_library.user_id
     *
     * @mbggenerated Fri Sep 08 10:18:39 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}