package com.cn.model.domain;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbggenerated Fri Sep 15 15:44:28 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.roleName
     *
     * @mbggenerated Fri Sep 15 15:44:28 CST 2017
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.resource_ids
     *
     * @mbggenerated Fri Sep 15 15:44:28 CST 2017
     */
    private String resourceIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.function_ids
     *
     * @mbggenerated Fri Sep 15 15:44:28 CST 2017
     */
    private String functionIds;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbggenerated Fri Sep 15 15:44:28 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbggenerated Fri Sep 15 15:44:28 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.roleName
     *
     * @return the value of role.roleName
     *
     * @mbggenerated Fri Sep 15 15:44:28 CST 2017
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.roleName
     *
     * @param rolename the value for role.roleName
     *
     * @mbggenerated Fri Sep 15 15:44:28 CST 2017
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.resource_ids
     *
     * @return the value of role.resource_ids
     *
     * @mbggenerated Fri Sep 15 15:44:28 CST 2017
     */
    public String getResourceIds() {
        return resourceIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.resource_ids
     *
     * @param resourceIds the value for role.resource_ids
     *
     * @mbggenerated Fri Sep 15 15:44:28 CST 2017
     */
    public void setResourceIds(String resourceIds) {
        this.resourceIds = resourceIds == null ? null : resourceIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.function_ids
     *
     * @return the value of role.function_ids
     *
     * @mbggenerated Fri Sep 15 15:44:28 CST 2017
     */
    public String getFunctionIds() {
        return functionIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.function_ids
     *
     * @param functionIds the value for role.function_ids
     *
     * @mbggenerated Fri Sep 15 15:44:28 CST 2017
     */
    public void setFunctionIds(String functionIds) {
        this.functionIds = functionIds == null ? null : functionIds.trim();
    }
}