package com.cn.model.entity;

import java.util.Date;

public class CustomerScanningCopy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_scanning_copy.id
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_scanning_copy.order_num
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_scanning_copy.file_md5
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    private String fileMd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_scanning_copy.file_suffix
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    private String fileSuffix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_scanning_copy.file_preview
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    private String filePreview;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_scanning_copy.file_path
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_scanning_copy.file_type
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    private String fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_scanning_copy.min_file_md5
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    private String minFileMd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_scanning_copy.min_file_preview
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    private String minFilePreview;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_scanning_copy.min_file_path
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    private String minFilePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_scanning_copy.create_time
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_scanning_copy.repair_time
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    private Date repairTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_scanning_copy.is_auto_upload
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    private Boolean isAutoUpload;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_scanning_copy.id
     *
     * @return the value of customer_scanning_copy.id
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_scanning_copy.id
     *
     * @param id the value for customer_scanning_copy.id
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_scanning_copy.order_num
     *
     * @return the value of customer_scanning_copy.order_num
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_scanning_copy.order_num
     *
     * @param orderNum the value for customer_scanning_copy.order_num
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_scanning_copy.file_md5
     *
     * @return the value of customer_scanning_copy.file_md5
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    public String getFileMd5() {
        return fileMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_scanning_copy.file_md5
     *
     * @param fileMd5 the value for customer_scanning_copy.file_md5
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    public void setFileMd5(String fileMd5) {
        this.fileMd5 = fileMd5 == null ? null : fileMd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_scanning_copy.file_suffix
     *
     * @return the value of customer_scanning_copy.file_suffix
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    public String getFileSuffix() {
        return fileSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_scanning_copy.file_suffix
     *
     * @param fileSuffix the value for customer_scanning_copy.file_suffix
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    public void setFileSuffix(String fileSuffix) {
        this.fileSuffix = fileSuffix == null ? null : fileSuffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_scanning_copy.file_preview
     *
     * @return the value of customer_scanning_copy.file_preview
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    public String getFilePreview() {
        return filePreview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_scanning_copy.file_preview
     *
     * @param filePreview the value for customer_scanning_copy.file_preview
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    public void setFilePreview(String filePreview) {
        this.filePreview = filePreview == null ? null : filePreview.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_scanning_copy.file_path
     *
     * @return the value of customer_scanning_copy.file_path
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_scanning_copy.file_path
     *
     * @param filePath the value for customer_scanning_copy.file_path
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_scanning_copy.file_type
     *
     * @return the value of customer_scanning_copy.file_type
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_scanning_copy.file_type
     *
     * @param fileType the value for customer_scanning_copy.file_type
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_scanning_copy.min_file_md5
     *
     * @return the value of customer_scanning_copy.min_file_md5
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    public String getMinFileMd5() {
        return minFileMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_scanning_copy.min_file_md5
     *
     * @param minFileMd5 the value for customer_scanning_copy.min_file_md5
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    public void setMinFileMd5(String minFileMd5) {
        this.minFileMd5 = minFileMd5 == null ? null : minFileMd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_scanning_copy.min_file_preview
     *
     * @return the value of customer_scanning_copy.min_file_preview
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    public String getMinFilePreview() {
        return minFilePreview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_scanning_copy.min_file_preview
     *
     * @param minFilePreview the value for customer_scanning_copy.min_file_preview
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    public void setMinFilePreview(String minFilePreview) {
        this.minFilePreview = minFilePreview == null ? null : minFilePreview.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_scanning_copy.min_file_path
     *
     * @return the value of customer_scanning_copy.min_file_path
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    public String getMinFilePath() {
        return minFilePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_scanning_copy.min_file_path
     *
     * @param minFilePath the value for customer_scanning_copy.min_file_path
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    public void setMinFilePath(String minFilePath) {
        this.minFilePath = minFilePath == null ? null : minFilePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_scanning_copy.create_time
     *
     * @return the value of customer_scanning_copy.create_time
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_scanning_copy.create_time
     *
     * @param createTime the value for customer_scanning_copy.create_time
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_scanning_copy.repair_time
     *
     * @return the value of customer_scanning_copy.repair_time
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    public Date getRepairTime() {
        return repairTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_scanning_copy.repair_time
     *
     * @param repairTime the value for customer_scanning_copy.repair_time
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    public void setRepairTime(Date repairTime) {
        this.repairTime = repairTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_scanning_copy.is_auto_upload
     *
     * @return the value of customer_scanning_copy.is_auto_upload
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    public Boolean getIsAutoUpload() {
        return isAutoUpload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_scanning_copy.is_auto_upload
     *
     * @param isAutoUpload the value for customer_scanning_copy.is_auto_upload
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    public void setIsAutoUpload(Boolean isAutoUpload) {
        this.isAutoUpload = isAutoUpload;
    }
}