package com.cn.model.entity;

import java.util.Date;

public class FileUploadSigning {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_confirm_signing.id
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_confirm_signing.order_num
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_confirm_signing.operator_empno
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    private String operatorEmpno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_confirm_signing.bank_name
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_confirm_signing.bank_branch_name
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    private String bankBranchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_confirm_signing.bank_card_number
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    private String bankCardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_confirm_signing.bank_bame_code
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    private String bankBameCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_confirm_signing.mobile
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_confirm_signing.account_i_d
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    private String accountID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_confirm_signing.binding_i_d
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    private String bindingID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_confirm_signing.quartet_agreement_file_path
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    private String quartetAgreementFilePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_confirm_signing.withhold_file_path
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    private String withholdFilePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_confirm_signing.network_loan_sample_path
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    private String networkLoanSamplePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_confirm_signing.delegation_path
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    private String delegationPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_confirm_signing.iou_path
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    private String iouPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_confirm_signing.repayment_reminder
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    private String repaymentReminder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_confirm_signing.upload_iou_path
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    private String uploadIouPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_confirm_signing.upload_verification_form
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    private String uploadVerificationForm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_confirm_signing.upload_other_contract
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    private String uploadOtherContract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_confirm_signing.upload_face_audit_img
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    private String uploadFaceAuditImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_confirm_signing.repayment_payment_day
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    private String repaymentPaymentDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_confirm_signing.repayment_start_date
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    private String repaymentStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_confirm_signing.repayment_current_day
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    private String repaymentCurrentDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_confirm_signing.repayment_end_date
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    private String repaymentEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_confirm_signing.create_time
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_confirm_signing.id
     *
     * @return the value of customer_confirm_signing.id
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_confirm_signing.id
     *
     * @param id the value for customer_confirm_signing.id
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_confirm_signing.order_num
     *
     * @return the value of customer_confirm_signing.order_num
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_confirm_signing.order_num
     *
     * @param orderNum the value for customer_confirm_signing.order_num
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_confirm_signing.operator_empno
     *
     * @return the value of customer_confirm_signing.operator_empno
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public String getOperatorEmpno() {
        return operatorEmpno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_confirm_signing.operator_empno
     *
     * @param operatorEmpno the value for customer_confirm_signing.operator_empno
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public void setOperatorEmpno(String operatorEmpno) {
        this.operatorEmpno = operatorEmpno == null ? null : operatorEmpno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_confirm_signing.bank_name
     *
     * @return the value of customer_confirm_signing.bank_name
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_confirm_signing.bank_name
     *
     * @param bankName the value for customer_confirm_signing.bank_name
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_confirm_signing.bank_branch_name
     *
     * @return the value of customer_confirm_signing.bank_branch_name
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public String getBankBranchName() {
        return bankBranchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_confirm_signing.bank_branch_name
     *
     * @param bankBranchName the value for customer_confirm_signing.bank_branch_name
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public void setBankBranchName(String bankBranchName) {
        this.bankBranchName = bankBranchName == null ? null : bankBranchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_confirm_signing.bank_card_number
     *
     * @return the value of customer_confirm_signing.bank_card_number
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public String getBankCardNumber() {
        return bankCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_confirm_signing.bank_card_number
     *
     * @param bankCardNumber the value for customer_confirm_signing.bank_card_number
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public void setBankCardNumber(String bankCardNumber) {
        this.bankCardNumber = bankCardNumber == null ? null : bankCardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_confirm_signing.bank_bame_code
     *
     * @return the value of customer_confirm_signing.bank_bame_code
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public String getBankBameCode() {
        return bankBameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_confirm_signing.bank_bame_code
     *
     * @param bankBameCode the value for customer_confirm_signing.bank_bame_code
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public void setBankBameCode(String bankBameCode) {
        this.bankBameCode = bankBameCode == null ? null : bankBameCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_confirm_signing.mobile
     *
     * @return the value of customer_confirm_signing.mobile
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_confirm_signing.mobile
     *
     * @param mobile the value for customer_confirm_signing.mobile
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_confirm_signing.account_i_d
     *
     * @return the value of customer_confirm_signing.account_i_d
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public String getAccountID() {
        return accountID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_confirm_signing.account_i_d
     *
     * @param accountID the value for customer_confirm_signing.account_i_d
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public void setAccountID(String accountID) {
        this.accountID = accountID == null ? null : accountID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_confirm_signing.binding_i_d
     *
     * @return the value of customer_confirm_signing.binding_i_d
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public String getBindingID() {
        return bindingID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_confirm_signing.binding_i_d
     *
     * @param bindingID the value for customer_confirm_signing.binding_i_d
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public void setBindingID(String bindingID) {
        this.bindingID = bindingID == null ? null : bindingID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_confirm_signing.quartet_agreement_file_path
     *
     * @return the value of customer_confirm_signing.quartet_agreement_file_path
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public String getQuartetAgreementFilePath() {
        return quartetAgreementFilePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_confirm_signing.quartet_agreement_file_path
     *
     * @param quartetAgreementFilePath the value for customer_confirm_signing.quartet_agreement_file_path
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public void setQuartetAgreementFilePath(String quartetAgreementFilePath) {
        this.quartetAgreementFilePath = quartetAgreementFilePath == null ? null : quartetAgreementFilePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_confirm_signing.withhold_file_path
     *
     * @return the value of customer_confirm_signing.withhold_file_path
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public String getWithholdFilePath() {
        return withholdFilePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_confirm_signing.withhold_file_path
     *
     * @param withholdFilePath the value for customer_confirm_signing.withhold_file_path
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public void setWithholdFilePath(String withholdFilePath) {
        this.withholdFilePath = withholdFilePath == null ? null : withholdFilePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_confirm_signing.network_loan_sample_path
     *
     * @return the value of customer_confirm_signing.network_loan_sample_path
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public String getNetworkLoanSamplePath() {
        return networkLoanSamplePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_confirm_signing.network_loan_sample_path
     *
     * @param networkLoanSamplePath the value for customer_confirm_signing.network_loan_sample_path
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public void setNetworkLoanSamplePath(String networkLoanSamplePath) {
        this.networkLoanSamplePath = networkLoanSamplePath == null ? null : networkLoanSamplePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_confirm_signing.delegation_path
     *
     * @return the value of customer_confirm_signing.delegation_path
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public String getDelegationPath() {
        return delegationPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_confirm_signing.delegation_path
     *
     * @param delegationPath the value for customer_confirm_signing.delegation_path
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public void setDelegationPath(String delegationPath) {
        this.delegationPath = delegationPath == null ? null : delegationPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_confirm_signing.iou_path
     *
     * @return the value of customer_confirm_signing.iou_path
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public String getIouPath() {
        return iouPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_confirm_signing.iou_path
     *
     * @param iouPath the value for customer_confirm_signing.iou_path
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public void setIouPath(String iouPath) {
        this.iouPath = iouPath == null ? null : iouPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_confirm_signing.repayment_reminder
     *
     * @return the value of customer_confirm_signing.repayment_reminder
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public String getRepaymentReminder() {
        return repaymentReminder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_confirm_signing.repayment_reminder
     *
     * @param repaymentReminder the value for customer_confirm_signing.repayment_reminder
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public void setRepaymentReminder(String repaymentReminder) {
        this.repaymentReminder = repaymentReminder == null ? null : repaymentReminder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_confirm_signing.upload_iou_path
     *
     * @return the value of customer_confirm_signing.upload_iou_path
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public String getUploadIouPath() {
        return uploadIouPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_confirm_signing.upload_iou_path
     *
     * @param uploadIouPath the value for customer_confirm_signing.upload_iou_path
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public void setUploadIouPath(String uploadIouPath) {
        this.uploadIouPath = uploadIouPath == null ? null : uploadIouPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_confirm_signing.upload_verification_form
     *
     * @return the value of customer_confirm_signing.upload_verification_form
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public String getUploadVerificationForm() {
        return uploadVerificationForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_confirm_signing.upload_verification_form
     *
     * @param uploadVerificationForm the value for customer_confirm_signing.upload_verification_form
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public void setUploadVerificationForm(String uploadVerificationForm) {
        this.uploadVerificationForm = uploadVerificationForm == null ? null : uploadVerificationForm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_confirm_signing.upload_other_contract
     *
     * @return the value of customer_confirm_signing.upload_other_contract
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public String getUploadOtherContract() {
        return uploadOtherContract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_confirm_signing.upload_other_contract
     *
     * @param uploadOtherContract the value for customer_confirm_signing.upload_other_contract
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public void setUploadOtherContract(String uploadOtherContract) {
        this.uploadOtherContract = uploadOtherContract == null ? null : uploadOtherContract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_confirm_signing.upload_face_audit_img
     *
     * @return the value of customer_confirm_signing.upload_face_audit_img
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public String getUploadFaceAuditImg() {
        return uploadFaceAuditImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_confirm_signing.upload_face_audit_img
     *
     * @param uploadFaceAuditImg the value for customer_confirm_signing.upload_face_audit_img
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public void setUploadFaceAuditImg(String uploadFaceAuditImg) {
        this.uploadFaceAuditImg = uploadFaceAuditImg == null ? null : uploadFaceAuditImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_confirm_signing.repayment_payment_day
     *
     * @return the value of customer_confirm_signing.repayment_payment_day
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public String getRepaymentPaymentDay() {
        return repaymentPaymentDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_confirm_signing.repayment_payment_day
     *
     * @param repaymentPaymentDay the value for customer_confirm_signing.repayment_payment_day
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public void setRepaymentPaymentDay(String repaymentPaymentDay) {
        this.repaymentPaymentDay = repaymentPaymentDay == null ? null : repaymentPaymentDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_confirm_signing.repayment_start_date
     *
     * @return the value of customer_confirm_signing.repayment_start_date
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public String getRepaymentStartDate() {
        return repaymentStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_confirm_signing.repayment_start_date
     *
     * @param repaymentStartDate the value for customer_confirm_signing.repayment_start_date
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public void setRepaymentStartDate(String repaymentStartDate) {
        this.repaymentStartDate = repaymentStartDate == null ? null : repaymentStartDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_confirm_signing.repayment_current_day
     *
     * @return the value of customer_confirm_signing.repayment_current_day
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public String getRepaymentCurrentDay() {
        return repaymentCurrentDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_confirm_signing.repayment_current_day
     *
     * @param repaymentCurrentDay the value for customer_confirm_signing.repayment_current_day
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public void setRepaymentCurrentDay(String repaymentCurrentDay) {
        this.repaymentCurrentDay = repaymentCurrentDay == null ? null : repaymentCurrentDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_confirm_signing.repayment_end_date
     *
     * @return the value of customer_confirm_signing.repayment_end_date
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public String getRepaymentEndDate() {
        return repaymentEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_confirm_signing.repayment_end_date
     *
     * @param repaymentEndDate the value for customer_confirm_signing.repayment_end_date
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public void setRepaymentEndDate(String repaymentEndDate) {
        this.repaymentEndDate = repaymentEndDate == null ? null : repaymentEndDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_confirm_signing.create_time
     *
     * @return the value of customer_confirm_signing.create_time
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_confirm_signing.create_time
     *
     * @param createTime the value for customer_confirm_signing.create_time
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}