package com.cn.model.entity;

import java.util.Date;

public class FileUpload {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload.id
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload.name
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload.md5
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    private String md5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload.path
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload.file_size
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    private Long fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload.suffix
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    private String suffix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload.create_time
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_upload.id
     *
     * @return the value of file_upload.id
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_upload.id
     *
     * @param id the value for file_upload.id
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_upload.name
     *
     * @return the value of file_upload.name
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_upload.name
     *
     * @param name the value for file_upload.name
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_upload.md5
     *
     * @return the value of file_upload.md5
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_upload.md5
     *
     * @param md5 the value for file_upload.md5
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    public void setMd5(String md5) {
        this.md5 = md5 == null ? null : md5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_upload.path
     *
     * @return the value of file_upload.path
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_upload.path
     *
     * @param path the value for file_upload.path
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_upload.file_size
     *
     * @return the value of file_upload.file_size
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_upload.file_size
     *
     * @param fileSize the value for file_upload.file_size
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_upload.suffix
     *
     * @return the value of file_upload.suffix
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_upload.suffix
     *
     * @param suffix the value for file_upload.suffix
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix == null ? null : suffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_upload.create_time
     *
     * @return the value of file_upload.create_time
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_upload.create_time
     *
     * @param createTime the value for file_upload.create_time
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}