package com.cn.model.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_name
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_code
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    private String productCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_type
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    private String productType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.original_price
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    private BigDecimal originalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.present_price
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    private BigDecimal presentPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.favorable_rate
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    private String favorableRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sales_volumes
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    private String salesVolumes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.inventory
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    private String inventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.monthly_sales
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    private String monthlySales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_status
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    private Integer productStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.business
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    private String business;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.create_time
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.last_time
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    private Date lastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.brand
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.profiles
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    private String profiles;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_name
     *
     * @return the value of product.product_name
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_name
     *
     * @param productName the value for product.product_name
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_code
     *
     * @return the value of product.product_code
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_code
     *
     * @param productCode the value for product.product_code
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_type
     *
     * @return the value of product.product_type
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public String getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_type
     *
     * @param productType the value for product.product_type
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public void setProductType(String productType) {
        this.productType = productType == null ? null : productType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.original_price
     *
     * @return the value of product.original_price
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public BigDecimal getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.original_price
     *
     * @param originalPrice the value for product.original_price
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public void setOriginalPrice(BigDecimal originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.present_price
     *
     * @return the value of product.present_price
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public BigDecimal getPresentPrice() {
        return presentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.present_price
     *
     * @param presentPrice the value for product.present_price
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public void setPresentPrice(BigDecimal presentPrice) {
        this.presentPrice = presentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.favorable_rate
     *
     * @return the value of product.favorable_rate
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public String getFavorableRate() {
        return favorableRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.favorable_rate
     *
     * @param favorableRate the value for product.favorable_rate
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public void setFavorableRate(String favorableRate) {
        this.favorableRate = favorableRate == null ? null : favorableRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sales_volumes
     *
     * @return the value of product.sales_volumes
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public String getSalesVolumes() {
        return salesVolumes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sales_volumes
     *
     * @param salesVolumes the value for product.sales_volumes
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public void setSalesVolumes(String salesVolumes) {
        this.salesVolumes = salesVolumes == null ? null : salesVolumes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.inventory
     *
     * @return the value of product.inventory
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public String getInventory() {
        return inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.inventory
     *
     * @param inventory the value for product.inventory
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public void setInventory(String inventory) {
        this.inventory = inventory == null ? null : inventory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.monthly_sales
     *
     * @return the value of product.monthly_sales
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public String getMonthlySales() {
        return monthlySales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.monthly_sales
     *
     * @param monthlySales the value for product.monthly_sales
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public void setMonthlySales(String monthlySales) {
        this.monthlySales = monthlySales == null ? null : monthlySales.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_status
     *
     * @return the value of product.product_status
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public Integer getProductStatus() {
        return productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_status
     *
     * @param productStatus the value for product.product_status
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public void setProductStatus(Integer productStatus) {
        this.productStatus = productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.business
     *
     * @return the value of product.business
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public String getBusiness() {
        return business;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.business
     *
     * @param business the value for product.business
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public void setBusiness(String business) {
        this.business = business == null ? null : business.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.create_time
     *
     * @return the value of product.create_time
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.create_time
     *
     * @param createTime the value for product.create_time
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.last_time
     *
     * @return the value of product.last_time
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.last_time
     *
     * @param lastTime the value for product.last_time
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.brand
     *
     * @return the value of product.brand
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.brand
     *
     * @param brand the value for product.brand
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.profiles
     *
     * @return the value of product.profiles
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public String getProfiles() {
        return profiles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.profiles
     *
     * @param profiles the value for product.profiles
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    public void setProfiles(String profiles) {
        this.profiles = profiles == null ? null : profiles.trim();
    }
}