package com.cn.model.entity;

import java.io.Serializable;

public class ShopAppCustomer implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_app_customer.ID
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_app_customer.CUSTOMER_NAME
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_app_customer.CUSTOMER_AGE
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    private String customerAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_app_customer.CUSTOMER_DELIVERY_ADRESS
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    private String customerDeliveryAdress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_app_customer.CUSTOMER_ID_CARD
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    private String customerIdCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_app_customer.CUSTOMER_BANK_CARD
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    private String customerBankCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_app_customer.IS_BANK_CARD
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    private String isBankCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_app_customer.IS_ID_CARD
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    private String isIdCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_app_customer.CUSTOMER_ACCOUNT_BALANCE
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    private String customerAccountBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_app_customer.CUSTOMER_CARD_COUPONS
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    private String customerCardCoupons;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_app_customer.IS_CARD_COUPONS
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    private String isCardCoupons;
    private String couponsPass;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_app_customer.ID
     *
     * @return the value of shop_app_customer.ID
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_app_customer.ID
     *
     * @param id the value for shop_app_customer.ID
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_app_customer.CUSTOMER_NAME
     *
     * @return the value of shop_app_customer.CUSTOMER_NAME
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_app_customer.CUSTOMER_NAME
     *
     * @param customerName the value for shop_app_customer.CUSTOMER_NAME
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_app_customer.CUSTOMER_AGE
     *
     * @return the value of shop_app_customer.CUSTOMER_AGE
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    public String getCustomerAge() {
        return customerAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_app_customer.CUSTOMER_AGE
     *
     * @param customerAge the value for shop_app_customer.CUSTOMER_AGE
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    public void setCustomerAge(String customerAge) {
        this.customerAge = customerAge == null ? null : customerAge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_app_customer.CUSTOMER_DELIVERY_ADRESS
     *
     * @return the value of shop_app_customer.CUSTOMER_DELIVERY_ADRESS
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    public String getCustomerDeliveryAdress() {
        return customerDeliveryAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_app_customer.CUSTOMER_DELIVERY_ADRESS
     *
     * @param customerDeliveryAdress the value for shop_app_customer.CUSTOMER_DELIVERY_ADRESS
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    public void setCustomerDeliveryAdress(String customerDeliveryAdress) {
        this.customerDeliveryAdress = customerDeliveryAdress == null ? null : customerDeliveryAdress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_app_customer.CUSTOMER_ID_CARD
     *
     * @return the value of shop_app_customer.CUSTOMER_ID_CARD
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    public String getCustomerIdCard() {
        return customerIdCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_app_customer.CUSTOMER_ID_CARD
     *
     * @param customerIdCard the value for shop_app_customer.CUSTOMER_ID_CARD
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    public void setCustomerIdCard(String customerIdCard) {
        this.customerIdCard = customerIdCard == null ? null : customerIdCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_app_customer.CUSTOMER_BANK_CARD
     *
     * @return the value of shop_app_customer.CUSTOMER_BANK_CARD
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    public String getCustomerBankCard() {
        return customerBankCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_app_customer.CUSTOMER_BANK_CARD
     *
     * @param customerBankCard the value for shop_app_customer.CUSTOMER_BANK_CARD
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    public void setCustomerBankCard(String customerBankCard) {
        this.customerBankCard = customerBankCard == null ? null : customerBankCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_app_customer.IS_BANK_CARD
     *
     * @return the value of shop_app_customer.IS_BANK_CARD
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    public String getIsBankCard() {
        return isBankCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_app_customer.IS_BANK_CARD
     *
     * @param isBankCard the value for shop_app_customer.IS_BANK_CARD
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    public void setIsBankCard(String isBankCard) {
        this.isBankCard = isBankCard == null ? null : isBankCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_app_customer.IS_ID_CARD
     *
     * @return the value of shop_app_customer.IS_ID_CARD
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    public String getIsIdCard() {
        return isIdCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_app_customer.IS_ID_CARD
     *
     * @param isIdCard the value for shop_app_customer.IS_ID_CARD
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    public void setIsIdCard(String isIdCard) {
        this.isIdCard = isIdCard == null ? null : isIdCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_app_customer.CUSTOMER_ACCOUNT_BALANCE
     *
     * @return the value of shop_app_customer.CUSTOMER_ACCOUNT_BALANCE
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    public String getCustomerAccountBalance() {
        return customerAccountBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_app_customer.CUSTOMER_ACCOUNT_BALANCE
     *
     * @param customerAccountBalance the value for shop_app_customer.CUSTOMER_ACCOUNT_BALANCE
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    public void setCustomerAccountBalance(String customerAccountBalance) {
        this.customerAccountBalance = customerAccountBalance == null ? null : customerAccountBalance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_app_customer.CUSTOMER_CARD_COUPONS
     *
     * @return the value of shop_app_customer.CUSTOMER_CARD_COUPONS
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    public String getCustomerCardCoupons() {
        return customerCardCoupons;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_app_customer.CUSTOMER_CARD_COUPONS
     *
     * @param customerCardCoupons the value for shop_app_customer.CUSTOMER_CARD_COUPONS
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    public void setCustomerCardCoupons(String customerCardCoupons) {
        this.customerCardCoupons = customerCardCoupons == null ? null : customerCardCoupons.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_app_customer.IS_CARD_COUPONS
     *
     * @return the value of shop_app_customer.IS_CARD_COUPONS
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    public String getIsCardCoupons() {
        return isCardCoupons;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_app_customer.IS_CARD_COUPONS
     *
     * @param isCardCoupons the value for shop_app_customer.IS_CARD_COUPONS
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    public void setIsCardCoupons(String isCardCoupons) {
        this.isCardCoupons = isCardCoupons == null ? null : isCardCoupons.trim();
    }

    public String getCouponsPass() {
        return couponsPass;
    }

    public void setCouponsPass(String couponsPass) {
        this.couponsPass = couponsPass;
    }
}