package com.cn.model.entity;

import java.io.Serializable;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ID
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USERNAME
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.LOGINACCOUNT
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    private String loginaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.REALNAME
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USERPASS
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    private String userpass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.VERIFICATIONCODE
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    private String verificationcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.INVITATIONCODE
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    private String invitationcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.MAILBOX
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    private String mailbox;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.SEX
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.CURRENTADDRESS
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    private String currentaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ISSUER
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    private String issuer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USERPHONE
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    private String userphone;

    private String jurisdiction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ID
     *
     * @return the value of user.ID
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ID
     *
     * @param id the value for user.ID
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USERNAME
     *
     * @return the value of user.USERNAME
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USERNAME
     *
     * @param username the value for user.USERNAME
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.LOGINACCOUNT
     *
     * @return the value of user.LOGINACCOUNT
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    public String getLoginaccount() {
        return loginaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.LOGINACCOUNT
     *
     * @param loginaccount the value for user.LOGINACCOUNT
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    public void setLoginaccount(String loginaccount) {
        this.loginaccount = loginaccount == null ? null : loginaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.REALNAME
     *
     * @return the value of user.REALNAME
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.REALNAME
     *
     * @param realname the value for user.REALNAME
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USERPASS
     *
     * @return the value of user.USERPASS
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    public String getUserpass() {
        return userpass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USERPASS
     *
     * @param userpass the value for user.USERPASS
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    public void setUserpass(String userpass) {
        this.userpass = userpass == null ? null : userpass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.VERIFICATIONCODE
     *
     * @return the value of user.VERIFICATIONCODE
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    public String getVerificationcode() {
        return verificationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.VERIFICATIONCODE
     *
     * @param verificationcode the value for user.VERIFICATIONCODE
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    public void setVerificationcode(String verificationcode) {
        this.verificationcode = verificationcode == null ? null : verificationcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.INVITATIONCODE
     *
     * @return the value of user.INVITATIONCODE
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    public String getInvitationcode() {
        return invitationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.INVITATIONCODE
     *
     * @param invitationcode the value for user.INVITATIONCODE
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    public void setInvitationcode(String invitationcode) {
        this.invitationcode = invitationcode == null ? null : invitationcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.MAILBOX
     *
     * @return the value of user.MAILBOX
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    public String getMailbox() {
        return mailbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.MAILBOX
     *
     * @param mailbox the value for user.MAILBOX
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    public void setMailbox(String mailbox) {
        this.mailbox = mailbox == null ? null : mailbox.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.SEX
     *
     * @return the value of user.SEX
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.SEX
     *
     * @param sex the value for user.SEX
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.CURRENTADDRESS
     *
     * @return the value of user.CURRENTADDRESS
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    public String getCurrentaddress() {
        return currentaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.CURRENTADDRESS
     *
     * @param currentaddress the value for user.CURRENTADDRESS
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    public void setCurrentaddress(String currentaddress) {
        this.currentaddress = currentaddress == null ? null : currentaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ISSUER
     *
     * @return the value of user.ISSUER
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    public String getIssuer() {
        return issuer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ISSUER
     *
     * @param issuer the value for user.ISSUER
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    public void setIssuer(String issuer) {
        this.issuer = issuer == null ? null : issuer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USERPHONE
     *
     * @return the value of user.USERPHONE
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    public String getUserphone() {
        return userphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USERPHONE
     *
     * @param userphone the value for user.USERPHONE
     *
     * @mbggenerated Fri Jun 09 11:04:56 CST 2017
     */
    public void setUserphone(String userphone) {
        this.userphone = userphone == null ? null : userphone.trim();
    }

    public String getJurisdiction() {
        return jurisdiction;
    }

    public void setJurisdiction(String jurisdiction) {
        this.jurisdiction = jurisdiction == null ? null :jurisdiction.trim() ;
    }
}