package com.cn.mapper;

import com.cn.model.entity.CustomerScanningCopy;

import java.io.Serializable;

public interface CustomerScanningCopyMapper <T,S,PK extends Serializable> extends CommonMapper<T, S,PK>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_scanning_copy
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_scanning_copy
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    int insert(CustomerScanningCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_scanning_copy
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    int insertSelective(CustomerScanningCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_scanning_copy
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    CustomerScanningCopy selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_scanning_copy
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    int updateByPrimaryKeySelective(CustomerScanningCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_scanning_copy
     *
     * @mbggenerated Mon Aug 28 11:13:39 CST 2017
     */
    int updateByPrimaryKey(CustomerScanningCopy record);
}