package com.cn.mapper;

import com.cn.model.entity.FileUpload;

import java.io.Serializable;

public interface FileUploadMapper <T,S,PK extends Serializable> extends CommonMapper<T, S,PK>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    int insert(FileUpload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    int insertSelective(FileUpload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    T selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    int updateByPrimaryKeySelective(FileUpload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload
     *
     * @mbggenerated Wed Aug 23 15:03:31 CST 2017
     */
    int updateByPrimaryKey(FileUpload record);
}