package com.cn.mapper;

import com.cn.model.entity.FileUploadSigning;

import java.io.Serializable;

public interface FileUploadSigningMapper <T,S,PK extends Serializable> extends CommonMapper<T, S,PK>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_confirm_signing
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_confirm_signing
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    int insert(FileUploadSigning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_confirm_signing
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    int insertSelective(FileUploadSigning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_confirm_signing
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    FileUploadSigning selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_confirm_signing
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    int updateByPrimaryKeySelective(FileUploadSigning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_confirm_signing
     *
     * @mbggenerated Fri Aug 25 16:03:42 CST 2017
     */
    int updateByPrimaryKey(FileUploadSigning record);
}