package com.cn.mapper;

import com.cn.model.entity.Product;
import org.apache.ibatis.annotations.Param;

import java.io.Serializable;
import java.util.List;

public interface ProductMapper <T,S,PK extends Serializable> extends CommonMapper<T, S,PK>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    Product selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu Jun 22 14:07:23 CST 2017
     */
    int updateByPrimaryKey(Product record);

    List<Product> getAll();

    List<Product> getList(@Param("productName") String productName,
                          @Param("brand") String brand,
                          @Param("business") String business,
                          @Param("maxPrice") Integer maxPrice,
                          @Param("minPrice") Integer minPrice,
                          @Param("productStatus") String productStatus,
                          @Param("productType") String productType);
}