package com.cn.mapper;

import com.cn.model.entity.Role;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.annotations.Param;
import java.util.List;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Fri Jun 09 13:39:21 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Fri Jun 09 13:39:21 CST 2017
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Fri Jun 09 13:39:21 CST 2017
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Fri Jun 09 13:39:21 CST 2017
     */
    Role selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Fri Jun 09 13:39:21 CST 2017
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Fri Jun 09 13:39:21 CST 2017
     */
    int updateByPrimaryKey(Role record);

    List<Role> selectRoleList(RowBounds rowBounds, @Param("rolename") String  rolename);

    int getTotalCount();

    List<Role> getList();

    Role selectByEmployeeNumber(@Param("num")String num);
}