package com.cn.mapper;

import com.cn.model.entity.ShopAppCustomer;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface ShopAppCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_app_customer
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_app_customer
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    int insert(ShopAppCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_app_customer
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    int insertSelective(ShopAppCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_app_customer
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    ShopAppCustomer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_app_customer
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    int updateByPrimaryKeySelective(ShopAppCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_app_customer
     *
     * @mbggenerated Sat May 27 09:49:19 CST 2017
     */
    int updateByPrimaryKey(ShopAppCustomer record);

    int getTotalCount();

    List<ShopAppCustomer> shopAppCustomerList(RowBounds rowBounds);

    ShopAppCustomer login(ShopAppCustomer shopAppCustomer);

    ShopAppCustomer loginName(String customerName);
}

