package com.cn.mapper;

import com.cn.model.entity.SysResource;
import org.apache.ibatis.annotations.Param;

import java.util.List;
public interface SysResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Tue Jun 20 10:41:21 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Tue Jun 20 10:41:21 CST 2017
     */
    int insert(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Tue Jun 20 10:41:21 CST 2017
     */
    int insertSelective(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Tue Jun 20 10:41:21 CST 2017
     */
    SysResource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Tue Jun 20 10:41:21 CST 2017
     */
    int updateByPrimaryKeySelective(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Tue Jun 20 10:41:21 CST 2017
     */
    int updateByPrimaryKey(SysResource record);

    List<SysResource> menuTree();

    List<SysResource> getListByIds(@Param("item")List item);
}